### PR TITLE
Update license text in source headers and template defaults

### PR DESCRIPTION
**Pull request by Renegade334**

### CODE REVIEW

**Comment by chrismou** [comment]
What's the reasoning behind the proposed licence change, out of interest? The main difference is see between the two is removal of a clause that prevents you using contributors names when endorsing derived works...

**Comment by Renegade334** [comment]
chrismou: Because the actual license used in all Phergie v3 repos _is_ the 2-clause license, so this isn't a proposed license change; it's simply a correction to the source headers.

As an aside, the license URL used in the source headers etc. (http://phergie.org/license) is actually a link to the Wordpress GPLv2 license, which should probably be addressed!

**Comment by chrismou** [comment]
Ha! In that case, good spot! :-)

**Comment by elazar** [comment]
Thanks! :)

**Pull request merged**
